# Generated by Django 4.0.4 on 2022-05-25 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('image', models.ImageField(upload_to='uploads/', verbose_name='Image')),
                ('date_created', models.DateField(auto_now=True, verbose_name='Date Created')),
                ('allowed_friends', models.ManyToManyField(related_name='blog_post', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
